# Generated by Django 3.1.3 on 2020-12-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('orders_json', models.JSONField()),
            ],
        ),
    ]
